name: NekoMOTD
description: My First Spigot Plugin
version: 1.0.0
main: cn.xinyue_neko.NekoMOTD.Main
api-version: 1.13
author: XinYueNeko

commands:
  test:
    description: Test
    usage: /<command>